---

- name: Update package definitions
  apt:
    update_cache=yes
    cache_valid_time=3600

- name: Install Java
  apt:
    name="{{item}}"
    state=present
  with_items: java_packages

# vi:ts=2:sw=2:et:ft=yaml
